version: "3.8"

services:
  # === API DE RECEBIMENTO (WEBHOOKS) ===
  exagerado-app:
    build: .
    container_name: exagerado_backend
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - evolution-postgres
      - redis
    networks:
      - evolution-net

  # === WORKER DE INTELIGÊNCIA (TEMPORIZADOR/ESTATÍSTICAS) ===
  exagerado-worker:
    build: .
    container_name: exagerado_worker
    restart: always
    env_file: .env
    command: python main_stats.py  # <-- Aqui roda o seu loop de 30 min
    depends_on:
      - evolution-postgres
      - redis
    networks:
      - evolution-net

  # === EVOLUTION API ===
  api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:latest
    restart: always
    depends_on:
      - redis
      - evolution-postgres
    ports:
      - "8080:8080"
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    env_file: - .env
    expose:
      - "8080"

  # === FRONTEND MANAGER ===
  frontend:
    container_name: evolution_frontend
    image: evoapicloud/evolution-manager:latest
    restart: always
    ports:
      - "3000:80"
    networks:
      - evolution-net

  # === REDIS ===
  redis:
    container_name: evolution_redis
    image: redis:latest
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - evolution_redis:/data
    networks:
      - evolution-net

  # === POSTGRES ===
  evolution-postgres:
    container_name: evolution_postgres
    image: postgres:15-alpine # Alpine para economizar RAM
    restart: always
    env_file: - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - evolution-net

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:

networks:
  evolution-net:
    driver: bridge